#################################
# author : charlie
# time : 20200905
# usage : to visualize the xvg file generated by GROMACS in terminal
# command : python3 xvgshow.py filename.xvg -n123
# arguements:
#     filename.xvg : generated by GROMACS
#     column number: start with '-n', like '-n235' (optional)
#################################


import sys
import plotille


def cols_num_gen(cols):
    for i in range(1, len(cols)+1):
        yield i


def picture_oneplot(title, xlabel, ylabel, data, cols):
    for i in cols:
        fig = plotille.Figure()
        fig.color_mode = 'byte'
        fig.set_x_limits(min_=0)
        fig.width = 60
        fig.height= 20
        #fig.background = 0
        fig.plot(data[0][1:], data[i][1:],label=data[i][0])
        print()
        print(fig.show(legend=True))
        print("title = ", title)
        print("ylabel = ", ylabel)
        print("xlabel = ", xlabel)        
        print()


def xvg_deal(filename):
    with open(filename, 'r') as fo:
        content = fo.read()
    line_list = content.strip('\n').split('\n')
    column_num = len(line_list[-1].split())
    data = []
    for i in range(column_num):
        data.append([])
    data[0].append('time')
    title = "Null"
    xlabel = "Null"
    ylabel = "Null"
    for line in line_list:
        if line[0] == "@":
            if "title" in line:
                title_line = line.strip('"')
                if '"' in title_line:
                    title = title_line.split('"')[-1]
            elif "xaxis" in line:
                xlabel_line = line.strip('"')
                if '"' in xlabel_line:
                    xlabel = xlabel_line.split('"')[-1]
            elif "yaxis" in line:
                ylabel_line = line.strip('"')
                if '"' in ylabel_line:
                    ylabel = ylabel_line.split('"')[-1]
            elif "legend" in line and "@ s" in line:
                legend = line.strip('"').split('"')[-1]
                for i in range(1, column_num):
                    if len(data[i]) == 0:
                        data[i].append(legend)
                        break

        elif line[0] != '#' and line[0] != '@' and ('time' not in line):
            num_list = line.strip().split()
            for i in range(column_num):
                if len(data[i]) == 0:
                    data[i].append('no-legend')
                # data[i].append( round( float(num_list[i]), 2) )
                data[i].append(float(num_list[i]))

    return title, xlabel, ylabel, data


def main():
    command = [i for i in sys.argv]
    command.append(" ")
    command.reverse()
    command.pop()

    if len(command) != 1:
        filename = command.pop()
    else:
        print(" --> NO FILE !")
        return
    if filename == "-h":
        print("arguements:\n    filename.xvg : generated by GROMACS")
        print("    column number: start with '-n' and split \
number by ',', like '-n2,3,5' (optional)")
        print("e.g. python3 xvgshow.py filename.xvg -n1,2,3")
        return

    filename = filename.strip()
    title, xlabel, ylabel, data = xvg_deal(filename)
    try:
        title, xlabel, ylabel, data = xvg_deal(filename)
    except:
        print("== Wrong filename ==")

    cols = [i for i in range(1, len(data))]
    for cm in command:
        if cm[0] == '-':
            if cm[0:2] == '-n':
                cols_ori = [int(cm[2:][m]) for m in range(len(cm[2:]))]
                col = []
                for c in cols_ori:
                    if c in cols:
                        col.append(c)
                    elif c not in cols:
                        print("== column number " +
                              str(c) + " is out of range. ")
                cols = col
            else:
                print(" Wrong arguements which has been ignored ! ")
    ## data check block
    #for i in range(len(data[0])):
        #for j in range(len(data)):
            #print(data[j][i], end = ' ')
        #print(' ')
    picture_oneplot(title, xlabel, ylabel, data, cols)


if __name__ == '__main__':
    main()
